# OHB voacap-service proxy config for lighttpd
# Place at: /etc/lighttpd/conf-enabled/54-hc-firmware.conf
# Requires mod_proxy to be loaded:
#   sudo lighttpd-enable-mod hc-firmware
#   sudo service lighttpd restart

url.rewrite-once += (
    "^/ham/HamClock/(ESPHamClock.*\.zip)$" => "/ham/HamClock/ESPHamClock.pl?$1"
)
