# OHB voacap-service proxy config for lighttpd
# Place at: /etc/lighttpd/conf-enabled/55-sdo-movies.conf
# Requires mod_proxy to be loaded:
#   sudo lighttpd-enable-mod sdo-movies
#   sudo service lighttpd restart

url.rewrite-once += (
    "^/ham/HamClock/SDO/movies/(.*\.mp4)$" => "/ham/HamClock/SDO/movies/sdo-movies.pl?$1"
)

url.rewrite-once += (
    "^/ham/HamClock/SDO/movies/(.*\.mp4)$" => "/ham/HamClock/SDO/movies/moon-movies.pl?$1"
)
