# enabling this module enables diagnostic uploads
# in docker we create a tmpfs for saving files.
#
$HTTP["url"] =~ "^/ham/HamClock/diagnostic-logs/.*\.txt$" {
    $HTTP["request-method"] == "POST" {
        url.rewrite-once = ( "^(.*)$" => "/ham/HamClock/upload-diag-handler.pl?$1" )
    }
}
